version: '3'
services:
  web:
    build: .
    command: gunicorn gutenberg_api.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    env_file:
      - .env.prod

volumes:
  postgres_data_prod:
